### ISSUE TITLE
Map doesn't show bot

### ISSUE THREAD

**Issue by jonathanbalagot** [OpenPoGo/OpenPoGoBot#146] opened 2016-08-01 03:34 UTC
After launching the web map, everything is populated except the bot location. Am I missing something here? I made sure to fill in the username array and API key for userdata.js

http://i.imgur.com/phXQ4ff.png

Running master - e1bd866e7297663bb236efd719a4122543a4adc5

**Comment by wchill** [comment] 2016-08-01 03:35
Known issue, we haven't modified bot/web to talk to each other with events.

I'm working on it.

**Comment by andythorne** [comment] 2016-08-02 13:30
Duplicate of #124

**Closed as completed by andythorne** 2016-08-02 13:30 UTC
