### ISSUE TITLE
Bot thinks you are softbanned when you are not and closes

### ISSUE THREAD

**Issue by Reaver01** [OpenPoGo/OpenPoGoBot#53] opened 2016-07-24 18:29 UTC
### Expected Behavior

OpenPoGoBot will try to spin, if it can't it should walk away and not try to spin that for at least 5 mins.
### Actual Behavior

OpenPoGoBot Spins the same Stop multiple times, reports that you are softbanned, and closes
### Steps to Reproduce

Run OpenPoGoBot and wait for it to spin a Stop
### Other Information

Also reported here: https://github.com/OpenPoGo/OpenPoGoBot/pull/42
OS: Windows/Linux
Git Commit: Happening on latest commit: db376bb

**Comment by wchill** [comment] 2016-07-24 18:34
Is it possibly related to the "Try again later." message you get sometimes in the app?

**Comment by Maximum-throwaway** [comment] 2016-07-24 18:35
I can confirm this bug.

It's an issue if you already spun the stop and got things from it once, but it's already on cooldown.

An easy repro is the following:
- Start the bot in a location, wait for it to spin a stop and get things.
- kill the bot
- start it again in the same location, it will likely go to spin that same stop again
- OH NOES UR SOFTBAND.

**Comment by MaxLeiter** [comment] 2016-07-24 18:40
We should probably keep track of visited pokestops and their cool down and ignore them until they're usable

**Comment by Maximum-throwaway** [comment] 2016-07-24 18:43
Unless you're talking about saving them to a file, that won't work if you kill the bot and restart it.

I believe we already keep track of the stops spun in memory anyways.

I think the issue is that if it doesn't get anything from the stop, it doesn't bother marking the stop as "spun" and explodes.

**Comment by MaxLeiter** [comment] 2016-07-24 18:45
I think we should then remove the crash and just print a red warning or some equivalent

**Comment by Maximum-throwaway** [comment] 2016-07-24 18:46
Also worth noting if you comment out the exception, the bot just keeps trying to spin the stop over and over.

So the fix for this should also mark that stop as "spun" and move on as well as spitting a big red warning

**Comment by RedSparr0w** [comment] 2016-07-25 02:43
It should work saving it to a file just something like

just save the `pokestop_cooldown` to file along with stop id
check the list each time it is searching for a nearby stop
once `current_time > pokestop_cooldown` remove it from the list.

and anything on the list will be ignored.

Should work when restarting bot aswell?

edit: could also mark them as being on cooldown on the web map aswell

**Comment by epicblood** [comment] 2016-07-27 19:00
is there not a separate response from server for spin failed and spun but no reward?

**Comment by wchill** [comment] 2016-07-30 18:50
Has anyone gotten this error? I haven't gotten it myself for a few days.

**Comment by wchill** [comment] 2016-08-01 03:23
Closing since this error seems to have been fixed.

**Closed as completed by wchill** 2016-08-01 03:23 UTC
Labels: bug
