### ISSUE TITLE
Bot not writing to inventory, catchable and location json files

### ISSUE THREAD

**Issue by pokemon-masterbater** [OpenPoGo/OpenPoGoBot#124] opened 2016-07-30 21:22 UTC
### Expected Behavior

Bot write to inventory, catchable, and location json files inside the web folder
### Actual Behavior

Bot is not writing to the inventory, catchable and location json files located in the web folder anymore
### Steps to Reproduce

Run like normal
### Other Information

OS: Debian 8
Git Commit:

**Comment by wchill** [comment] 2016-07-30 21:42
This is intentional, currently pending a switch to websockets. Will push this code soon.

**Comment by pokemon-masterbater** [comment] 2016-07-30 21:47
Can I have some code for keeping json files? It works better for me

**Comment by wchill** [comment] 2016-07-30 22:31
The problem is that that same code breaks on certain Python versions, which is why it was removed.

You can try to run this commit https://github.com/OpenPoGo/OpenPoGoBot/commit/bd8432a6d689b9d6991378f5d43f3a27555d2a16 on Python 2.7 but it will have bugs that were fixed in master.

**Comment by pokemon-masterbater** [comment] 2016-07-30 22:41
Is there an easy method where I can at least write the bots location to a json file so my map can read it?

**Comment by wchill** [comment] 2016-08-09 10:42
Should no longer be necessary with the switch to OpenPoGoUI.

**Closed as completed by wchill** 2016-08-09 10:42 UTC
Labels: bug, priority
