### ISSUE TITLE
Not use 2 factor authentication but still Login Error, server busy

### ISSUE THREAD

**Issue by yusufRahmatullah** [OpenPoGo/OpenPoGoBot#296] opened 2016-08-13 02:23 UTC
### Expected Behavior

login success
### Actual Behavior

Login Error, server busy
### Other Information

OS: Raspbian jessie
Git Commit: last commit

**Comment by wchill** [comment] 2016-08-13 03:40
Possible duplicate of #295.

**Comment by yusufRahmatullah** [comment] 2016-08-13 06:45
what is info that you needed?
oh yes, i'm trying to using bot in windows 8.1 and it's work

**Closed as completed** 2016-08-13 18:50 UTC
Labels: more info needed
