### ISSUE TITLE
Pokemon not transfered

### ISSUE THREAD

**Issue by epicblood** [OpenPoGo/OpenPoGoBot#216] opened 2016-08-07 22:35 UTC
### Expected Behavior

if pokemon is bellow cp & iv limit after catch, should get transferred for candy
### Actual Behavior

Pokemon is not transfered:

``` python
[2016-08-08 00:33:23] [Catch] Pidgey has been caught! (CP 98, IV 0.47)
[2016-08-08 00:33:23] [#] Added 3 candies for Pidgey
[2016-08-08 00:33:23] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-08 00:33:24] [Transfer] Transferring caught Pokemon with CP NOT above 400 and IV NOT above 0.7 and excluding [''].
[2016-08-08 00:33:24] [Transfer] No Pokemon to transfer.
[2016-08-08 00:33:24] [Transfer] Transferred 0 Pokemon.
```
### Steps to Reproduce

Run bot till encounter pokemon with low cp & iv

**Comment by wchill** [comment] 2016-08-07 23:31
Can't reproduce:

```
[2016-08-07 16:31:01] [Catch] A wild Rattata appeared! [CP 79] [Potential 0.42]
[2016-08-07 16:31:04] [Catch] Using Pokeball... (8 left!)
[2016-08-07 16:31:04] [Catch] Rattata has been caught! (CP 79, IV 0.42)
[2016-08-07 16:31:04] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-07 16:31:04] [Transfer] Transferring caught Pokemon with CP NOT above 1000 and IV NOT above 0.9 and excluding [''].
[2016-08-07 16:31:04] [Transfer] Transferring Rattata (#19) with CP 79 and IV 0.42 (1/1)
[2016-08-07 16:31:06] [Transfer] Transferred 1 Pokemon.
```

**Comment by tegob** [comment] 2016-08-08 06:35
I am getting the same issue. Not sure how to reproduce it exactly but it happened to me three times now.

```
[2016-08-08 15:28:58] [Transfer] Transferred 0 Pokemon.
[2016-08-08 15:29:05] [Catch] Pokemon bag is full; cannot catch.
[2016-08-08 15:29:05] [Transfer] Transferring all Pokemon with CP NOT above 100 and IV NOT above 0.9 and excluding [''].
[2016-08-08 15:29:05] [Transfer] No Pokemon to transfer.
[2016-08-08 15:29:05] [Transfer] Transferred 0 Pokemon.
[2016-08-08 15:29:05] [PokeStop] Nearby PokeStop found "XXX" (0.01km away)
[2016-08-08 15:29:05] [PokeStop] Spinning...
[2016-08-08 15:29:07] [PokeStop] Item bag is full.
[2016-08-08 15:29:11] [Catch] Pokemon bag is full; cannot catch.
[2016-08-08 15:29:11] [Transfer] Transferring all Pokemon with CP NOT above 100 and IV NOT above 0.9 and excluding [''].
[2016-08-08 15:29:11] [Transfer] No Pokemon to transfer.
[2016-08-08 15:29:11] [Transfer] Transferred 0 Pokemon.
[2016-08-08 15:29:17] [Navigation] Arrived at PokeStop "XXX" (0.08km away)
^C
[2016-08-08 15:29:17] [x] Exiting PokemonGo Bot
```

When restarting the bot, everything is transferred successfully (assuming `"initial_transfer": true`):

```
[2016-08-08 15:29:20] [x] PokemonGO Bot v1.0
[2016-08-08 15:29:20] [x] Configuration initialized
[2016-08-08 15:29:20] [Plugins] Not loading plugin "web"
[2016-08-08 15:29:20] [Plugins] Loaded plugin "recycle_items".
[2016-08-08 15:29:20] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-08 15:29:20] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-08 15:29:20] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-08 15:29:20] [Plugins] Loaded plugin "egg_incubator".
[2016-08-08 15:29:22] [Plugins] Plugins loaded: ['catch_pokemon', 'egg_incubator', 'recycle_items', 'spin_pokestop', 'transfer_pokemon']
[2016-08-08 15:29:22] [Events] Events available: ['incubate_egg', 'item_bag_full', 'logging', 'pokemon_bag_full', 'pokemon_caught', 'pokemon_found', 'pokestop_arrived', 'pokestops_found', 'set_campsite', 'transfer_pokemon', 'walking_started', 'waypoint_add', 'waypoint_remove']
[2016-08-08 15:29:22]
[2016-08-08 15:29:22] [x] Last location flag used. Overriding passed in location
[2016-08-08 15:29:22] [x] Last in-game location was set as: (XXX, YYY, 0.0)
[2016-08-08 15:29:22]
[2016-08-08 15:29:23] [+] Login to Pokemon Go successful.
[2016-08-08 15:29:24] [#]
[2016-08-08 15:29:24] [#] Username: XXX
[2016-08-08 15:29:24] [#] Acccount Creation: XXX
[2016-08-08 15:29:24] [#] Bag Storage: 350/350
[2016-08-08 15:29:24] [#] Pokemon Storage: 248/250
[2016-08-08 15:29:24] [#] Stardust: 98125
[2016-08-08 15:29:24] [#] Pokecoins: 0
[2016-08-08 15:29:24] [#] PokeBalls: 50
[2016-08-08 15:29:24] [#] GreatBalls: 194
[2016-08-08 15:29:24] [#] UltraBalls: 0
[2016-08-08 15:29:24] [#] -- Level: XXX
[2016-08-08 15:29:24] [#] -- Experience: XXX
[2016-08-08 15:29:24] [#] -- Experience until next level: XXX
[2016-08-08 15:29:24] [#] -- Pokemon Captured: XXX
[2016-08-08 15:29:24] [#] -- Pokestops Visited: XXX
[2016-08-08 15:29:24] [Transfer] Transferring all Pokemon with CP NOT above 300 and IV NOT above 0.9 and excluding [''].
[2016-08-08 15:29:24] [Transfer] Transferring Magikarp (#129) with CP 118 and IV 0.87 (1/166)
[…]
```

Workaround is to `kill` the bot every now and then and restart it.

**Comment by wchill** [comment] 2016-08-08 07:20
@tegob in your logs it seems the CP settings are different?

**Comment by tegob** [comment] 2016-08-08 07:41
Ah, good catch. I was tweaking the settings last night so the bot might still have been running with the old config. I’ll keep an eye on it and will report back if it happens again.

@epicblood Maybe it helps to post the location you’re botting at?

**Comment by epicblood** [comment] 2016-08-08 10:07
Running bot in central park, will check again today to make sure not a fluke

**Comment by tegob** [comment] 2016-08-09 06:44
Happened again today. To reproduce just lower the CP and IV settings and wait until your Pokémon storage is full. The bot should be able to figure out it’s looping indefinitely and do _something_ (even if it’s just shutting down), IMHO. Perhaps automatically increase the `cp` setting by 100 when this occurs?

**Comment by wchill** [comment] 2016-08-09 08:48
Yeah, the filtering can use some improvements for sure.

**Comment by epicblood** [comment] 2016-08-10 16:33
This still happens intermittently, cant get a steps-to-reproduce 100% though

**Comment by ajurna** [comment] 2016-08-10 22:14
changes in #268 should help with this.

**Comment by meyer9** [comment] 2016-08-16 04:33
Reopen if still an issue.

**Closed as completed by meyer9** 2016-08-16 04:33 UTC
Labels: bug, help
