### ISSUE TITLE
[APi] Requesting too fast.

### ISSUE THREAD

**Issue by banaszeknorbert** [OpenPoGo/OpenPoGoBot#198] opened 2016-08-03 22:01 UTC
This happens after successful logging. I'm getting this:
[2016-08-03 23:57:21] [x] Starting PokemonGo Bot....
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
Does anyone have a similar problem? Is Niantic changed something in the api?

**Comment by ghost** [comment] 2016-08-03 22:14
same here since about 2 hours

**Comment by banaszeknorbert** [comment] 2016-08-03 22:20
Ok, I found this: https://www.reddit.com/r/pokemongo/comments/4vvpbw/niantic_is_upping_the_scan_refresh_rate_to_break/

Could someone tell me where I can change this value?

**Comment by wchill** [comment] 2016-08-03 22:21
All bots are broken at the moment. Nothing we can do right now.

**Comment by banaszeknorbert** [comment] 2016-08-03 22:23
Increasing the refresh rate will not work?

**Comment by MaxLeiter** [comment] 2016-08-03 22:25
Duplicate of #153

**Closed as completed by MaxLeiter** 2016-08-03 22:25 UTC

**Comment by wchill** [comment] 2016-08-07 08:08
Not actually a duplicate of #153, but fixed in #202.
