### ISSUE TITLE
Bot not evolving Pokemon

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoBot#260] opened 2016-08-10 15:23 UTC
### Expected Behavior

Evolve Pidgey/Rattata/Spearow/Weedle on catch/transfer.
### Actual Behavior

Nothing happens.
### Steps to Reproduce

Relevant portions of my config.json:
`"evolve_pokemon": true,

```
"evolve_filter": [
    "Pidgey",
    "Rattata",
    "Spearow",
    "Weedle"
]`
```

When starting the bot, it says the the evolver plugin is loaded:
`[2016-08-10 11:12:28] [Plugins] Loaded plugin "evolver".`
### Other Information

OS: Ubuntu 16.04
Git Commit: fa63364

**Comment by epicblood** [comment] 2016-08-10 16:29
are you sure you have enough candies to evolve those?

**Comment by ghost** [comment] 2016-08-10 16:37
I have almost 1000 Pidgey candies, and hundreds for the others as well.

**Comment by xasdf** [comment] 2016-08-10 19:23
I can confirm this. I think it started happening after commit c244185efab2aff996d929fe8a37d981534736f3 but maybe I'm wrong. Granted it was crashing before that fix because array element was accessed after free.

[2016-08-10 11:59:12] [Catch] Pidgey has been caught! (CP 151, IV 0.51, CPM 0.399567276239)
[2016-08-10 11:59:12] [#] Added 3 candies for Pidgey
[2016-08-10 11:59:12] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-10 11:59:12] [Transfer] Transferring Pidgey (#16) with CP 151 and IV 0.51 (1/1)
[2016-08-10 11:59:14] [#] Added 1 candies for Pidgey
[2016-08-10 11:59:14] [Evolver] Stopped evolving due to error
[2016-08-10 11:59:14] [Transfer] Transferred 1 Pokemon.

(I have modified my copy of code a bit so that it doesn't spam "Transferring Pokemon with CP NOT above and IV NOT above" every time).

Looks like it's getting transferred (due to low stats) before evolve. Maybe it's easier to repro if you set a fairly aggressive transfer policy such that pretty much everything needs to be transferred. Also looks like it's happening to Pidgeys only for some strange reason.

**Comment by epicblood** [comment] 2016-08-10 20:40
@lazydox do you also the 'stopped evolving due to error` log?

**Comment by epicblood** [comment] 2016-08-10 20:49
was broken in #241, will PR a fix in a minute after I verify it all works

**Comment by ghost** [comment] 2016-08-10 21:51
@epicblood no, I do not appear to have any logs related to evolving whatsoever. Although, I just had a thought... is it supposed to just be evolve on transfer only, or also evolve on catch? Because currently I'm not transferring any Pokemon.

**Comment by epicblood** [comment] 2016-08-10 22:46
@lazydox @KristsKrilovs try my PR (#269) it should work

**Comment by xasdf** [comment] 2016-08-10 23:25
@epicblood fix works - it now evolves pokemons from evolve_filter correctly.
Maybe unrelated issue (as I don't think this worked correctly before) - After pokemon is auto-evolved it should be added to transfer list. Currently that is not happening. If it happens to evolve multiple then it does seem to transfer according to log but I'm not sure if it actually is happening:

Multiple evolutions (note the weird output below):
[2016-08-10 16:16:52] [Catch] Pidgey has been caught! (CP 317, IV 0.64, CPM 0.566754519939)
[2016-08-10 16:16:52] [#] Added 3 candies for Pidgey
[2016-08-10 16:16:52] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-10 16:16:53] [Evolver] Evolved Pidgey into Pidgeotto
[2016-08-10 16:16:55] [Evolver] Evolved Pidgey into Pidgeotto
[2016-08-10 16:16:57] [Evolver] Evolved 2 Pidgey(s)
[2016-08-10 16:16:57] [Transfer] Transferring Pidgey (#16) with CP 317 and IV 0.64 (1/1)
[2016-08-10 16:16:59] [#] Added 1 candies for Pidgey
[2016-08-10 16:16:59] [Evolver] Evolved 0 Pidgey(s)
[2016-08-10 16:16:59] [Transfer] Transferred 1 Pokemon.

Single evolution (most common case, no transfer):
[2016-08-10 16:20:25] [Catch] Pidgey has been caught! (CP 107, IV 0.31, CPM 0.349212676287)
[2016-08-10 16:20:25] [#] Added 3 candies for Pidgey
[2016-08-10 16:20:25] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-10 16:20:25] [Evolver] Evolved Pidgey into Pidgeotto
[2016-08-10 16:20:28] [Evolver] Evolved 1 Pidgey(s)
[2016-08-10 16:20:28] [Transfer] No Pokemon to transfer.
[2016-08-10 16:20:28] [Transfer] Transferred 0 Pokemon.

**Comment by epicblood** [comment] 2016-08-10 23:27
it will only transfer if the evolved pokemon's cp/IV is below your transfer threshold, it does not get added to a list to auto transfer.

**Comment by xasdf** [comment] 2016-08-10 23:39
No, that's not it, they are below transfer threshold. I can verify that by restarting bot with initial_transfer set to true and then they all transfer on startup.

**Comment by xasdf** [comment] 2016-08-11 01:03
Anyway, the transfer on auto-evolve is a separate issue. It probably is a no-issue because eventually bad pokemons will get transferred on pokemon_bag_full event.

PR (#269) fixes this bug for me.

**Closed as completed** 2016-08-12 01:08 UTC
