### ISSUE TITLE
Crash with initial-transfer enabled and pokemons not available

### ISSUE THREAD

**Issue by hanseartic** [OpenPoGo/OpenPoGoBot#111] opened 2016-07-29 09:02 UTC
### Expected Behavior

The bot should start without crash when `-it` is given as option but certain pokemons are not available.
### Actual Behavior

```
$  ./pokecli.py -j config.json -lc -it -cp 200
{'username': u'XXX@gmail.com', 'max_steps': 100000, 'recycle_items': True, 'initial_transfer': True, u'evolve_all': True, u'item_filter': {u'201': {u'keep': 30}, u'701': {u'keep': 100}, u'1': {u'keep': 50}, u'102': {u'keep': 30}, u'103': {u'keep': 30}, u'101': {u'keep': 10}}, 'distance_unit': u'km', 'exclude_plugins': [u'web'], 'auth_service': u'google', 'walk': 4.16, 'debug': False, 'json': 'config.json', 'test': False, 'location': u'54.179776, 7.889137', 'ign_init_trans': '', 'location_cache': True, 'cp': 200, 'password': u'***', 'gmapkey': u'XXX', 'pokemon_potential': 0.7, 'mode': u'all'}
…
[2016-07-29 10:59:20] [x] Initial Transfer.
[2016-07-29 10:59:20] [x] Will NOT transfer anything above CP 200 or these ['']
Traceback (most recent call last):
  File "./pokecli.py", line 240, in <module>
    main()
  File "./pokecli.py", line 228, in main
    bot.start()
  File "~/OpenPoGoBot/pokemongo_bot/__init__.py", line 55, in start
    self._setup_api()
  File "~/OpenPoGoBot/pokemongo_bot/__init__.py", line 250, in _setup_api
    worker.work()
  File "~/OpenPoGoBot/pokemongo_bot/cell_workers/initial_transfer_worker.py", line 23, in work
    pokemon_groups = self._initial_transfer_get_groups()
  File "~/OpenPoGoBot/pokemongo_bot/cell_workers/initial_transfer_worker.py", line 57, in _initial_transfer_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
```
### Steps to Reproduce

Start bot with `-it`, stop it and immediately start second time with `-it`.
### Other Information

OS: OSX Yosemite (python 2.7.11 and python 3.5.2)
Git Commit: d61d555

**Comment by dbmurphy** [comment] 2016-07-29 10:46
Duplicate of #109

**Comment by JulianMBr** [comment] 2016-07-29 11:18
We will merge this with the #109 as @dbmurphy referenced. Thank you!

**Closed as completed by JulianMBr** 2016-07-29 11:18 UTC
Labels: duplicate
