### ISSUE TITLE
made bot working through proxy

### ISSUE THREAD

**Issue by maithanhtan** [OpenPoGo/OpenPoGoBot#239] opened 2016-08-09 08:04 UTC
Hi,
Due to limit of niantic allow 1 account per ip. Can you made the proxy option to run account on each proxy.
Thanks

**Comment by wchill** [comment] 2016-08-09 08:14
Duplicate of #235. Use a system-wide proxy or VPN if you need this.

**Closed as completed by wchill** 2016-08-09 08:14 UTC
