### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by adventurer** [OpenPoGo/OpenPoGoBot#151] opened 2016-08-01 06:01 UTC
File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 68, in walk_to
    self._do_walk_to(speed, position_lat, position_lng, lat, lng, alt, 25)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 94, in _do_walk_to
    self._work_at_position(position_lat, position_lng)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 137, in _work_at_position
    self.bot.work_on_cell(cell)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/__init__.py", line 90, in work_on_cell
    walk_worker.work()
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/cell_workers/walk_towards_fort_worker.py", line 62, in work
    self.stepper.walk_to(self.config.walk, _position)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 68, in walk_to
    self._do_walk_to(speed, position_lat, position_lng, lat, lng, alt, 25)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 94, in _do_walk_to
    self._work_at_position(position_lat, position_lng)
  File "/home/wwwroot/pokemon/OpenPoGoBot/pokemongo_bot/stepper.py", line 123, in _work_at_position
    response_dict = self.api_wrapper.call()
  File "/home/wwwroot/pokemon/OpenPoGoBot/api/__init__.py", line 96, in call
    results = request.call()
  File "/home/wwwroot/pokemon/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 177, in call
    request = RpcApi(self._auth_provider)
  File "/home/wwwroot/pokemon/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 56, in __init__
    self._session = requests.session()
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 689, in session
    return Session()
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 346, in __init__
    self.mount('https://', HTTPAdapter())
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 109, in **init**
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 145, in init_poolmanager
    block=block, strict=True, *_pool_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 66, in **init**
    dispose_func=lambda p: p.close())
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/_collections.py", line 47, in __init__
    self._container = self.ContainerCls()
  File "/usr/local/lib/python2.7/collections.py", line 57, in __init__
    self.**update(_args, *_kwds)
  File "/usr/local/lib/python2.7/abc.py", line 151, in __subclasscheck**
    if subclass in cls._abc_cache:
  File "/usr/local/lib/python2.7/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RuntimeError: maximum recursion depth exceeded

**Comment by wchill** [comment] 2016-08-01 06:09
Duplicate of #147.

**Closed as completed by wchill** 2016-08-01 06:09 UTC
